[[redirects]]
  from = "/proxy/*"
  to = "https://fixed-jacenta-memoonoffice.koyeb.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "http://diaryimghj.s3-website.ap-northeast-2.amazonaws.com/:splat"
  status = 200
  force = true
  headers = {  Access-Control-Allow-Origin = "*"}


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"