[[redirects]]
  from = "/proxy/*"
  to = "https://fixed-jacenta-memoonoffice.koyeb.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "https://daily-diary-happy.netlify.app/:splat"
  to = "https://s3.amazonaws.com/%27diaryimghj%27/upload/:splat"
  status = 200
  force = true
  headers = {  Access-Control-Allow-Origin = "*"}


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"